### ISSUE TITLE
Missing ontologyTerm.json?

### ISSUE THREAD

**Issue by mshadbolt** [ga4gh-beacon/beacon-v2-Models#104]
Hello,

While parsing the `common` schemas I found that there doesn't exist a schema in the repo for `ontologyTerm.json` here https://github.com/ga4gh-beacon/beacon-v2-Models/tree/main/BEACON-V2-Model/common even though when you follow this link it does exist https://raw.githubusercontent.com/ga4gh-beacon/beacon-framework-v2/main/common/ontologyTerm.json. 

Not sure if I am missing where this schema exists as a file in the repo structure?

Thanks in advance!

Marion

**Comment by mshadbolt** [comment]
never mind, just realised this schema is defined in the framework repo rather than the model repo weirdly. Sorry for the bother.

**Comment by mbaudis** [comment]
@mshadbolt You found it :-) But this is a bit confusing, I guess. We're about to have both framework and models in the https://github.com/ga4gh-beacon/beacon-v2 repository (in fact, they are already mirrored there, but issues/PRs still being processed here for the next days/weeks). Also: Documentation now at  https://ga4gh-beacon.github.io/beacon-v2/, aliased at http://docs.genomebeacons.org.

**Comment by mshadbolt** [comment]
Oh thanks for pointing out the new combined repo and the fancy new docs website, very helpful thanks :)
