### ISSUE TITLE
aachange -> aminoacidSubstitution

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2-Models#25]
The `aachange ` parameter name is odd and not in line with general attempts to stick w/ readability... We have longer names already :-) (`pathologicalTnmFinding`, `sampleOriginDetail` ...) so let's just use `aminoacidSubstitution`.

https://github.com/ga4gh-beacon/beacon-v2-Models/blob/5136123994e19c505ef1c6360369c38b8fcc3af9/BEACON-V2-draft4-Model/genomicVariations/requestParameters.json#L64

**Comment by mbaudis** [comment]
Also: `aminoacidChanges` is being used [elsewhere](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/5136123994e19c505ef1c6360369c38b8fcc3af9/BEACON-V2-draft4-Model/genomicVariations/defaultSchema.json#L163):

```
    "MolecularAttributes": {
      "geneIds": {
        "type": "array",
        "items": "string"
      },
...
      "aminoacidChanges": {
        "description": "Lisf of change(s) at aminoacid level for protein affecting variants.",
        "type": "array",
        "items": {
          "type": "string"
        },
        "example": ["V304*"]
      }
    },
```

**Comment by jrambla** [comment]
@mbaudis the style used should be (except errors or omissions):
- long names for properties in the schemas 
- long names for parameters in Request boby
- shorter names for parameters in the query  string 
Therefore, the plan was not to use long names everywhere, ;-)    although in most of the places.
Makes sense?
