### ISSUE TITLE
[Q] variants start / end fuzzy range.

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2-Models#34]
Hello,

In the draft4 variants Position.start / end are defined as an array ("examples": ["[1000], [1000,1100]"]):
https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-draft4-Model/genomicVariations/defaultSchema.json
I understand the logic for the request parameters (to provide "fuzzy" search), but for the Beacon what is the meaning? Is this for structural variants?
I see the current Beacon 2 draft implementation and do not see it is reflected in the database ("variant_table" start / end int4).
https://github.com/EGA-archive/beacon-2.x/

Cheers,

Dmitry

**Comment by jrambla** [comment]
I'm confused.
Aren't we using the brtacketed queries in the example queries document?
Aren't we talking about that here?

**Comment by redmitry** [comment]
No. One thing is a fuzzy query (requestParameters ?) and another range position in the found beacon.
I do not object, but the meaning may be different - for the query, we search for beacons those start position is within a range.
For the concrete beacon "fuzzy" position should mean different thing.
Is this related to the:
~~~
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS for imprecise variants">
##INFO=<ID=CIEND,Number=2,Type=Integer,Description="Confidence interval around END for imprecise variants">
~~~
?
I took a look at the CRG implementation and found that it is still a number in the postgres database.

Cheers,

Dmitry
