### ISSUE TITLE
[Q] Individuals defaultSchema "Measure" definition.

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2-Models#37]
Hello,

In the individuals [defaultSchema.json](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-draft4-Model/individuals/defaultSchema.json) there is a definition of "Measure" object:
~~~json
"definitions": {
  "Measure": {
    "description": "Measures(s) been taken from Individual. ...",
    "type": "object",
~~~
On the other hand, "mesures" property uses [measurement.json](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-draft4-Model/common/measurement.json):
~~~json
"measures": {
  "type": "array",
  "items": {
    "$ref": "../common/measurement.json"
  }
},
~~~
It looks like the "Measure" definition is not used anymore and is an artifact left from the draft-3.

Dmitry

**Comment by jrambla** [comment]
Good catch. Solved
