### ISSUE TITLE
frequencyPopulations

### ISSUE THREAD

**Issue by rahelp** [ga4gh-beacon/beacon-v2-Models#46]
why is this not a child of variant level data? in genomicVariation default schema

**Comment by mbaudis** [comment]
@jrambla Sure, this is an option - but then the population frequencies have to go there, too.

### 3-tier variation model

1. individual variant observations per sample/experiment
  * `variantInSample`, ` callsetVariant`, `variantObservation` or however it should be named
  * describes / links to information from a given patient / experiment
  * corresponds to callset column intersection with variant line in VCF
  * additionally offers option to present/link to patient specific data like observed phenotype, disease association, treatment etc.
2. aggregate variant information from given dataset / resource / cohort
  * corresponds to / possibly derived from "line in VCF"
  * general information about the variant "prototype", w/o the per sample details
  * aggregate data, like frequency / count in dataset
  * additional offers option to link to resource local clinical conclusions (e.g. asserted variant effect, lists of phenotypes ...)
3. dataset external information / evidences
  * reported variant effect, clinical impact, druggability ...
  * frequencies in populations / studies / cohorts
  * can include resource local data (e.g. frequencies in other datasets of the same resource ...)
  * ClinGen, ClinVar, Cosmic ...

### 2-tier model

Collapse 2&3 from above, but then have disambiguation between the response specific (e.g. frequency in the queried scope, local evaluation of clin. impact) and general evidence
