### ISSUE TITLE
"Sequencing Run" -> "Experimental Run" or other more neutral

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2-Models#49]
https://github.com/ga4gh-beacon/beacon-v2-Models/blob/b2af8bb9dc0ac5f2a16836f58fad1f5389d6de65/BEACON-V2-draft4-Model/runs/defaultSchema.json#L3

Many experiments behind variant calls are not done by sequencing. In the same scope, "sequencing" should be replaced where more general wording fits.

**Comment by jrambla** [comment]
I would be happy if you can contribute with a suggestion that is broad and clear enough...
