### ISSUE TITLE
required attributes in Individuals and genomicVariations models

### ISSUE THREAD

**Issue by colinveal** [ga4gh-beacon/beacon-v2-Models#6]
Hi all, just querying the required fields for Individuals and genomicVariations

Individuals Model currently has "individualId" and "sex" as required, however queries would not necessarily need to include either of these fields, ie searching for any individual with a specific disease.

genomicVariatoins Model  "variantId" and "AlternateBases" shouldn't be required for a range query
cheers

**Comment by jrambla** [comment]
HI Colin, the "required" applies to the response payload, not to the the query/request (unless I'm missing something here).
Therefore you can query (don't pay attention to the syntax): /individuals?filters:HPO:1234  and get back a list of individuals that should contain "id" and "sex" for each one.
Similarly (idem): /g_variants?start:1,end:10 and get back a list of variants for which you should provide the "id" and the "AlternateBases".
Makes sense?

**Comment by colinveal** [comment]
yes that makes sense thanks
