### ISSUE TITLE
Fix missing colons in recent datasets/defaultSchema.json change

### ISSUE THREAD

**Issue by jlfernandez-cba** [ga4gh-beacon/beacon-v2-Models#60]
Commit ebd8f04141d45e93e357424034931e58406c06bd

`https://github.com/ga4gh-beacon/beacon-v2-Models/commit/ebd8f04141d45e93e357424034931e58406c06bd#`

which added date-time format definitions, introduced a couple of syntax errors in datasets/defaultSchema.json. Specifically, a pair of colons are missing from lines 21 and 27.

**Comment by mbaudis** [comment]
@jlfernandez-cba Hilarious, in a bad way. I've looked at this for... a long time and just didn't see. Well push... Thanks!

**Comment by mbaudis** [comment]
Fixed in https://github.com/ga4gh-beacon/beacon-v2-Models/commit/06a961c1e85c41e8c9eeba9a73dec7c543f52e27 .

**Comment by jlfernandez-cba** [comment]
I was tempted to write "formatting improvement introduced bad formatting typo" XD
Thanks a lot, Michael.
