### ISSUE TITLE
clinVarIds type should be array

### ISSUE THREAD

**Issue by mrueda** [ga4gh-beacon/beacon-v2-Models#62]
Hi there,

In line 136 we have the property "clinVarIds" defined as "type" = "string".

Being a plural name (and by looking at the examples), it looks like "type" should be "array" and then "items" should be defined as "string". This way the definition will match the examples given.

Cheers,

Manu

**Comment by mbaudis** [comment]
Solved in https://github.com/ga4gh-beacon/beacon-v2-Models/commit/f53c08327e085eb67dfc690f91b0844ac8571b6e => `clinvarId` (singular) + better definition of alternate Ids.
