### ISSUE TITLE
individual-MID-example is not updated to the draft4

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2-Models#66]
Hello,

I see the [age.json](BEACON-V2-draft4-Model/common/age.json) has changed the format between draft3 and draft4.

~~~yaml
Age:
      type: object
      properties:
        age:
          type: string
          example: 'P32Y6M1D'
        ageGroup:
          type: string
          example: 'NCIT:C27954 (Adolescent)'
~~~
vs (new):
~~~json
{
  "title": "Age",
  "type": "object",
  "properties": {
    "iso8601duration": {
      "type": "string",
      "example": "P32Y6M1D"
    }
  }
}
~~~

Example files must be updated accordingly:
[individual-MID-example.json](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/08cb436eed0534e380487652279cb29597cd9d16/BEACON-V2-draft4-Model/individuals/examples/individual-MID-example.json#L22-L27)

Current schema(s):
[**Individual**](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/08cb436eed0534e380487652279cb29597cd9d16/BEACON-V2-draft4-Model/individuals/defaultSchema.json#L25-L31)

~~~json
{
  "title": "Individual",
  "type": "object",
  "properties": {
    "diseases": {
      "type": "array",
      "items": {
        "$ref": "../common/disease.json"
      }
~~~

[**Disease**](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/08cb436eed0534e380487652279cb29597cd9d16/BEACON-V2-draft4-Model/common/disease.json#L16-L18)
~~~
{
  "title": "Disease",
  "type": "object",
  "properties": {
    "ageOfOnset": {
      "$ref": "./age.json"
    },
~~~

Cheers,

Dmitry

**Comment by Tom-Shorter** [comment]
It might make sense to change ageOfOnset (not just in disease) to reference one of age.json or ageRange.json as well as fixing the example, @redmitry, @mbaudis do you agree?

**Comment by redmitry** [comment]
> It might make sense to change ageOfOnset (not just in disease) to reference one of age.json or ageRange.json as well as fixing the example, @redmitry, @mbaudis do you agree?

The only place where "ageOfOnset" property is defined is in the [disease.json](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/disease.json) and it is `"$ref": "./age.json"`.
The only thing that is needed the change is the example.

**Comment by mbaudis** [comment]
`ageOfOnset` compares to the Phenopackets `onset` and should be a `timeElement`, where `age` and `ageGroup` then represent options.

* <https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/timeElement.json>
* <https://phenopacket-schema.readthedocs.io/en/latest/time-element.html#rsttimeelement>

**Comment by redmitry** [comment]
OIC. On the other hang timeElement is quite generic. Be more specific vs more Phenopackets, I am afraid I not qualified to opinion here.

**Comment by mbaudis** [comment]
There you go https://github.com/ga4gh-beacon/beacon-v2-Models/pull/77 . Does this work? @redmitry @Tom-Shorter

**Comment by redmitry** [comment]
The age is defined as:

~~~json
{
  "properties": {
    "iso8601duration": {
      "type": "string",
    }
  }
}
~~~
So the example
~~~json
 "examples": [
        { "ageGroup": { "id": "NCIT:C49685", "label": "Adult 18-65 Years Old" }, "age": "P32Y6M1D"},
        { "ageRange": { "start": "P18Y", "end": "P59Y" } },
        { "age": "P2M4D"}
      ]
~~~
is invalid, should be:
~~~json
{ "ageRange": { "start": {"iso8601duration": "P18Y"}, "end": {"iso8601duration": "P59Y" }} },
{ "age":  {"iso8601duration": "P2M4D"}}
~~~

**Comment by mbaudis** [comment]
@redmitry Well caught - and there are (wee) more of these... Fixed in https://github.com/ga4gh-beacon/beacon-v2-Models/commit/9b74a7e8b17ae8724d837451ad26d21662c3baa6, I hope?!

**Comment by redmitry** [comment]
I think it is ok now.
