### ISSUE TITLE
Phenopackets differences & alignment

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2-Models#68]
In the current data models, many schemas are either directly compatible to
[Phenopackets v2 building blocks](https://phenopacket-schema.readthedocs.io/en/latest/building-blocks.html)
or at least reflect them in spirit. The following lists elements with notes
regarding their Phenopackets compatibility.

While the Beacon v2 default model's schemas do not _per se_ have to reflect
PXF schemas, we target an as-close-as-possible alignment to promote/leverage GA4GH-wide
standardization.

This issue here serves for a general review regarding current and possible future
alignment, with individual changes being processed in separate PRs/issues.

## Top-level differences

The Phenopackets model is centered around the `Phenopacket`, which is the collector
and integrator of all sub-schemas (with the addition of the external `Family` and
`Cohort` schemas). While `Phenopacket` usually describes information related to a
`subject` -  which is defined in an `Individual` - and the top level elements in
`Phenopacket` relate to a specific `proband` (`measurements` as "Measurements performed
in the proband"), the phenopacket itself does not explicitely _represent_ an individual.

In contrast, the Beacon v2 default model uses a hierarchy in which biosamples
reference individuals directly (if existing). For most purposes one can equate Beacon's
`Individual` with a merge of Phenopacket's core `Phenopacket` and `Individual` parameters. 

### `Age`

* [PXF Age](https://phenopacket-schema.readthedocs.io/en/latest/age.html)
* [Beacon v2 Age](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/age.json)

### `AgeRange`

* [PXF AgeRange](https://phenopacket-schema.readthedocs.io/en/latest/age.html#agerange)
* [Beacon v2 AgeRange](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/ageRange.json)

### `Evidence`

* [PXF Evidence](https://phenopacket-schema.readthedocs.io/en/latest/evidence.html)
* [Beacon v2 Evidence](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/evidence.json)

### `KaryotypicSex`

* [PXF](https://github.com/phenopackets/phenopacket-schema/blob/master/docs/karyotypicsex.rst)
* [Beacon](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/commonDefinitions.json#L15)

### `ReferenceRange`

* [PXF ReferenceRange](https://phenopacket-schema.readthedocs.io/en/latest/reference-range.html)
* [Beacon v2 ReferenceRange](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/referenceRange.json)

While `unit` in Beacon points to a `Unit` definition, this is itself an `OntologyTerm` i.e. structurally the same.

### `Value`

* [PXF Value](https://phenopacket-schema.readthedocs.io/en/latest/value.html)
* [Beacon v2 Value](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/value.json)

### `ComplexValue `

* [PXF ComplexValue](https://phenopacket-schema.readthedocs.io/en/latest/complex-value.html)
* [Beacon v2 ComplexValue](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/complexValue.json)

Renamed `ComplexValue.TypedQuantity.quantityType` compared to GA4GH Phenopackets v2 `ComplexValue.TypedQuantity.type` due to problematic use of `type` as parameter

### `ExternalReference`

* [PXF ExternalReference](https://phenopacket-schema.readthedocs.io/en/latest/externalreference.html)
* [Beacon v2 ExternalReference](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/externalReference.json)

Renamed `ExternalReference.notes` compared to GA4GH Phenopackets v2 `ExternalReference.description` due to problematic use of `description` as parameter

### `Measurement`

* [PXF Measurement](https://phenopacket-schema.readthedocs.io/en/latest/measurement.html)
* [Beacon v2 Measurement](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/measurement.json)

Added `notes` and `date`.

### `PhenotypicFeature`

* [PXF PhenotypicFeature](https://phenopacket-schema.readthedocs.io/en/latest/phenotype.html)
* [Beacon v2 PhenotypicFeature](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/phenotypicFeature.json)

Beacon | Phenopackets
--------- | ------------
`featureType` | `type`
`severityLevel`  (re-used definition reflecting an ontology term) | `severity` (ontology class)
`notes` | 

### `Procedure `

* [PXF Procedure](https://phenopacket-schema.readthedocs.io/en/latest/procedure.html)
* [Beacon v2 Procedure](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/procedure.json)

Beacon | Phenopackets
--------- | ------------
`procedureCode` | `code`
`ageAtProcedure`  (TimeElement) | `performed ` (`TimeElement`)
`dateOfProcedure`  (ISO date) | 

### `TimeElement `

* [PXF TimeElement](https://phenopacket-schema.readthedocs.io/en/latest/time-element.html)
* [Beacon v2 TimeElement](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/timeElement.json)

The specific parameters have been aligned w/ some differences in naming or use of general parameters.

| Beacon | Phenopackets
|--------- | ------------
| `ageGroup` | `ontology_class `
| `age ` | `age ` (`Age`)
| `ageRange ` | `age_range ` (`AgeRange`)
| `gestationalAge`  | `gestational_age ` (`GestationalAge`)
|   | `timestamp ` (`TimeStamp`)
|   | `interval ` (`TimeInterval`)

### `Treatment `

* [PXF Treatment](https://phenopacket-schema.readthedocs.io/en/latest/treatment.html)
* [Beacon v2 Treatment](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/treatment.json)

Beacon still has an `ageOfOnset` parameter (?).

### `Pedigree`

While the Beacon & Phenopackets schemas for "pedigree" representation are not aligned, they may become superseded by the [GA4GH pedigree standard](https://github.com/GA4GH-Pedigree-Standard/pedigree) currenty under development.

### `Sex`

Beacon directly uses the (IMO preferable) [representation through an ontology term](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/539cb05dada755c7b1a66b2e187b9668fcfa670b/BEACON-V2-Model/common/commonDefinitions.json#L6), while PXF uses an [ordinal mapping](https://phenopacket-schema.readthedocs.io/en/latest/sex.html)

##### 2022-01-18: Updated w/ "Top-level differences"

**Comment by julesjacobsen** [comment]
Are the `Treatment` differences still correct? These look to be the same now e.g. they both use an array of `DoseInterval`.

**Comment by mbaudis** [comment]
@julesjacobsen Yes, the notes here were the initial comparison. While I've added some changes after adjustments we'll document the relation to Phenopackets in the documentation (https://github.com/ga4gh-beacon/beacon-v2-unity-testing/blob/main/docs/formats-standards.md or page linked from there).
(@mrueda @laurenfromont)

**Comment by mbaudis** [comment]
The comparison has been added to the documentation: <http://docs.genomebeacons.org/formats-standards/#phenopackets>.

We'll update there and through individual issues/PRs.
