### ISSUE TITLE
genomicVariant vs. genomicVariation

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2-Models#7]
While I like `genomicVariation` (used in the schema), the mix of `genomicVariant` vs. `genomicVariation` is confusing. I'd settle for one version.

https://github.com/ga4gh-beacon/beacon-v2-Models/blob/c6552b66d206601fb909074b11b690e300d0a0aa/BEACON-V2-draft4-Model/beaconConfiguration.json#L60

**Comment by jrambla** [comment]
Yes, I know, this was also an "experiment", like the "extendedInfo" one.
We are working on the "Variant Cluster" and come back with suggestion after the weekend.
