### ISSUE TITLE
VRS differences & alignment

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2-Models#70]
The GA4GH Variant Representation Standard (VRS) constitutes the reference one should use when implementing representations of genomic variations. The [current version 1.2](https://vrs.ga4gh.org/en/stable/releases/1.2.html) has been approved and covers a set of use cases and requirements, especially with respect to genomic (including cytogenetic or feature based) locations. However, it is not yet suitable for a number of practical use cases, especially the representation of most structural variations.

At this point (early 2022), VRS seems already well suited to replace the [`Position` schema](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/08cb436eed0534e380487652279cb29597cd9d16/BEACON-V2-draft4-Model/genomicVariations/defaultSchema.json#L64) in the current `genomicVariations` default schema with its `Location` schema.

Since VRS is a GA4GH standard, it seems to be relevant to a) either implement during the Beacon v2 approval process, or b) provide a timeline for a transition.

#### To do

Evaluate draft `Position` => VRS `Location`

##### Beacon v2 example (CNV)

```
{
  "position": {
    "assemblyId": "GRCh38",
    "end": [
      91643662
    ],
    "refseqId": "chr5",
    "start": [
      91586193
    ]
  },
  "variantInternalId": "5:91586193-91643662:DEL",
  "variantType": "DEL",
  "caseLevelData": [
    {
      "analysisId": "pgxcs-kftwfq4h",
      "biosampleId": "pgxbs-kftvj7cy",
      "id": "pgxvar-5c86661b09d374f2dc4e4a48"
    }
  ],

}
```

##### Example w/ VRS translation of `Position` => `Location`

There would be also  other options covering `start` or `end` with intervals.

```
{
  "location": {
    "type": "SequenceLocation",
    "interval": {
      "type": "SequenceInterval",
      "start": {
        "type": "Number",
        "value": 91586193
      },
      "end": {
        "type": "Number",
        "value": 91643662
      },
    },
    "sequenceId": "refseq:NC_000005.10",
   },
   "variantInternalId": "5:91586193-91643662:DEL",
   "variantType": "DEL",
   "caseLevelData": [
    {
      "analysisId": "pgxcs-kftwfq4h",
      "biosampleId": "pgxbs-kftvj7cy",
      "id": "pgxvar-5c86661b09d374f2dc4e4a48"
    }
  ]
}
```

##### CNV attributes from VRS

Adding the CNV parameters ... However, it should be noted that VRS currently lacks support for relative or class based representation of CNVs - discussion [here](https://github.com/ga4gh/vrs/issues/277).

```
{
  "location": {
    "type": "SequenceLocation",
    "interval": {
      "type": "SequenceInterval",
      "start": {
        "type": "Number",
        "value": 91586193
      },
      "end": {
        "type": "Number",
        "value": 91643662
      },
    },
    "sequenceId": "refseq:NC_000005.10",
   },
  "type": "CopyNumber",
    "copies": {
      "comparator": "<=",
      "type": "IndefiniteRange",
      "value": 1
    },
   "variantInternalId": "5:91586193-91643662:DEL",
   "caseLevelData": [
    {
      "analysisId": "pgxcs-kftwfq4h",
      "biosampleId": "pgxbs-kftvj7cy",
      "id": "pgxvar-5c86661b09d374f2dc4e4a48"
    }
  ]
}
```

##### SNV example

Here the near-complete representation of an SNV is provided.
* Question: Reference bases in VRS?

```
{
  "location": {
    "type": "SequenceLocation",
    "interval": {
      "type": "SequenceInterval",
      "start": {
        "type": "Number",
        "value": 112842175
      },
      "end": {
        "type": "Number",
        "value": 112842176
      },
    },
    "sequenceId": "refseq:NC_000005.10",
   },
  "state": {
    "sequence": "C",
    "type": "SequenceState"
  },
  "variantInternalId": "5:112842175-112842176:T>C",
  "referenceBases": "T",
  "caseLevelData": [
    {
      "analysisId": "celloscs-CVCL_1326",
      "biosampleId": "cellosbios-CVCL_1326",
      "id": "60ec58358711e3c54ce9f6a6"
    }
  ]
}
```

**Comment by mbaudis** [comment]
`Location` use in PR https://github.com/ga4gh-beacon/beacon-v2-Models/pulls

**Comment by ahwagner** [comment]
I think if we can fit `Location` and `Allele` into the Beacon Models we have captured the most important components for interoperability with respect to VRS. `Location` PR (#71) is a good approach.
