### ISSUE TITLE
Broken cross-repo references

### ISSUE THREAD

**Issue by gsfk** [ga4gh-beacon/beacon-v2-Models#75]
Hello! 

The Models and Frameworks repo mix url and relative path references in a way that leads to dead ends, at least for me. For example, the variants endpoints spec includes this reference to the spec for responses from a boolean beacon:

https://github.com/ga4gh-beacon/beacon-v2-Models/blob/08cb436eed0534e380487652279cb29597cd9d16/BEACON-V2-draft4-Model/genomicVariations/endpoints.json#L213

But the spec retrieved from that link contains _relative_ path references to code _inside_ the Frameworks repo:

[`"$ref": "./sections/beaconResponseMeta.json"`](https://github.com/ga4gh-beacon/beacon-framework-v2/blob/c44a685af8cd7a8bcadd7cd55d46fd8b2646a6c7/responses/beaconBooleanResponse.json#L9)

so the reference can't be resolved. This is only one example, there are several more with the same issue.

**Comment by mbaudis** [comment]
This is a general issue - can be fixed, but the logical thing would be to move to a unified repository https://github.com/ga4gh-beacon/beacon-v2-Models/issues/76#
