### ISSUE TITLE
Unified repository, naming, versioning...

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2-Models#76]
While the logical separation of framework and model makes sense, the practical separation into different repositories does more harm than good, IMO. It is very confusing for implementers/users, and also has problems in handling (relative references, documentation ...).

My recommendation would be one unified repository

```
beacon
  |
  |-- framework
  |-- models
  |-- docs
  |-- (tools / bin ...)
```

This doesn't mean that e.g. point releases would have to affect the framework or that framework & model cannot have independent versioning (though I would keep it simple).

Such a structure is also in line with other standards, make it easier to understand the project and allow for a simpler handling of issues and pull requests.

And the repos have to be renamed anyway, with update of alle references - so better let's do it right.

Discuss! Please :-)

(Btw., IMO "models", not singular, since there are several "independent" ones ...).

**Comment by gsfk** [comment]
+1 for this, which among other things would resolve the issue I filed previously (#75), as well as removing the `raw.githubusercontent` dependecies.

**Comment by mbaudis** [comment]
I have created a repository structure in https://github.com/ga4gh-beacon/beacon-v2-unity. This is empty so far, but will be populated with schemas pulled from the current repos, for testing.

Please indicate (dis-)agreements/opinions about the setup!

**Comment by mbaudis** [comment]
The https://github.com/ga4gh-beacon/beacon-v2-unity repository has now been populated _without any checks or edits_, from the current mode and framework repos. The conversion steps have been described in the README.

**Comment by d-salgado** [comment]
I believe that the naming may cause some confusion too. It should be beacon v2 without -unity when the unification is completed.

**Comment by mbaudis** [comment]
@d-salgado Exactly!

**Comment by jrambla** [comment]
This issue is actually discussed in #78

**Comment by mbaudis** [comment]
@jrambla Agree to go on with the discussion in #78 - but the issue here was the [establishment of a combined repo for framework + models + docs](https://github.com/ga4gh-beacon/beacon-v2-unity-testing) while #78 is about a deeper structuring for its [models part](https://github.com/ga4gh-beacon/beacon-v2-unity-testing/tree/main/models) (done in the current models repo to keep people engaged ...).
