### ISSUE TITLE
Gestational age

### ISSUE THREAD

**Issue by pnrobinson** [ga4gh-beacon/beacon-v2-Models#81]
Please consider adding support for gestational age
https://phenopacket-schema.readthedocs.io/en/latest/gestational-age.html
as a part of [time element](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/common/timeElement.json).
This would be extremely useful for our planned Beacon/Phenopacket use case

**Comment by mbaudis** [comment]
@pnrobinson Can you please check? Thanks! https://github.com/ga4gh-beacon/beacon-v2-Models/pull/84

**Comment by mbaudis** [comment]
Closed since #84
