### ISSUE TITLE
Representation of Treament

### ISSUE THREAD

**Issue by pnrobinson** [ga4gh-beacon/beacon-v2-Models#83]
It seems the major disadvatnage of the proposed beacon representation of treatment is that it is difficult to represent multiple time/age ranges of treatment, e.g., 

propranolol
2020-03-01 to 2020-04-01
and then
atenolol
2020-04-02 to 2020-04-27

since there is only a duration. It is also unusual to speak of "ageAtOnset" for a treatment.

**Comment by mbaudis** [comment]
@pnrobinson There you go -> ?
https://github.com/ga4gh-beacon/beacon-v2-Models/pull/85

**Comment by mbaudis** [comment]
Closed with #85
