### ISSUE TITLE
[Q] confusing documentation on the genomicVariations/endpoint.json

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2-Models#93]
Hello,

Two endpoints of the [genomicVariations/endpoints.json](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/genomicVariations/endpoints.json) have the description: "Get details about one dummyEntry, identified by its (unique) 'id'"
I suppose that it should be "genomic variant", because we getting it by the {id} ?

Cheers,

Dmitry

**Comment by mbaudis** [comment]
Thanks - fixed in https://github.com/ga4gh-beacon/beacon-v2-Models/commit/e11b14a328bba7888ee218fb750e53c14f7edd6d. 

Please check dependencies... Tagging some).

**Comment by mbaudis** [comment]
Closing since fix is simple & operation Ids are discussed elsewhere.
