### ISSUE TITLE
[Q] should all endpoint's GETs include includeResultsetResponses query param?

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2-Models#97]
Hello,  
Some endpoints include the includeResultsetResponses:  
`GET "/analyses"`  
`GET "/biosamples"`  
`GET "/g_variants"`  
`GET "/individuals"`  
`GET "/runs"`  
while others, not:  
`GET "/cohorts"`  
`GET "/datasets"`  
just to verify if this parameter missing or left out on purpose...

thank you,

Dmitry

**Comment by mbaudis** [comment]
These should have collectionResponses ...

**Comment by redmitry** [comment]
Agree. that was the very old one issue... 

IMHO :
[beaconCollectionsResponse.json](https://github.com/ga4gh-beacon/beacon-framework-v2/blob/fff90ba6b0f82564bcf14ddcf565e89934427c42/responses/beaconCollectionsResponse.json#L21)
~~~
    "response": {
      "description": "Returning the Beacon Collections list, filtered or unfiltered.",
      "type": "object",
      "properties": {
        "collections": {
          "type": "array",
          "items": {
            "type": "object"
          },
          "minItems": 0
        }
      },
      "required": ["collections"],
      "additionalProperties": true
    },
~~~ 
is not quite descriptive...

D.
